---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-prod
provisioner: cluster.local/nfs-server-nfs-server-provisioner
parameters:
  server: nfs-server
  path: /share
  readOnly: "false"