---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-app-backend
  labels:
    app: prod-backend
spec:
  selector:
    matchLabels:
      app: prod-backend
  template:
    metadata:
      labels:
        app: prod-backend
    spec:
      containers:
      - name: backend
        image: bitnami/prometheus
        ports:
        - containerPort: 9090
        env:
        - name: db_conn_string
          value: "Server=postgres-db.default.svc.cluster.local;Port=5432;Database=news;User Id=postgres;Password=postgres;"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: prod-backend
spec:    
  type: ClusterIP
  ports:
    - targetPort: 9090
      port: 9090
  selector:
    app: prod-backend
