

all:
  vars:
    ansible_connection: ssh
    ansible_user: ubuntu
  hosts:

    worker-node-0:
      ansible_host: 51.250.8.235
    worker-node-1:
      ansible_host: 51.250.3.112
    master-node: 
      ansible_host: 51.250.6.37
  children:
    kube_control_plane:
      hosts:
        master-node:
    kube_node:
      hosts:
        worker-node-0:
        worker-node-1:
        
    etcd:
      hosts:
        master-node:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}  
    